apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: eh8de06gj-python
  janus-idp.io/tekton: eh8de06gj-python
  backstage.io/kubernetes-id: eh8de06gj-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: eh8de06gj-python
resources:
- deployment.yaml
- route.yaml
- service.yaml
